### ISSUE TITLE
Possible to link to a glossary term from a redactor field?

### ISSUE THREAD

**Issue by CreateSean** [codemonauts/craft-glossary#3]
Is it possible to link to a glossary term from a redactor field and have it display as a tooltip?

**Comment by kringkaste** [comment]
You do not need to link a term manually in a redactor field. The plugin has a filter that will automatically find corresponding terms in the text and replace it with the tooltip.

If you do not want to use the filter, e.g. you only want to have one special occurrence of a term to be replaced with a tooltip and all other not, there is no solution at the moment. Is something like that the reason for your question?

**Comment by CreateSean** [comment]
@kringkaste No this now appears to do what I want. From the docs I didn't realize that I could use the filter on an entry field like `{{ entry.copy|glossary }}` though now that I see it, I should've known.

Thank you.

**Comment by kringkaste** [comment]
@CreateSean You are welcome :)
