### ISSUE TITLE
Term synonym field with trailing comma breaks frontend

### ISSUE THREAD

**Issue by storybynumbers** [codemonauts/craft-glossary#7]
If a term has a list of synonyms ending in a trailing comma, spaces will be treated as a synonym for that term. It results in broken HTML, and terms are replaced with with IDs instead of underlined words. See screenshots below. Removing the trailing comma resolves the issue.

Backend:

<img width="203" alt="Screen Shot 2022-06-30 at 16 46 07" src="https://user-images.githubusercontent.com/44193/176708907-45658f6a-e4a1-43f2-97fd-ab9e0e11f491.png">

Frontend:

<img width="489" alt="Screen Shot 2022-06-30 at 16 31 26" src="https://user-images.githubusercontent.com/44193/176709172-46f1dc79-3166-4f8b-a40b-e84eb676d883.png">

Rendered HTML:

![WhatsApp Image 2022-06-30 at 4 45 34 PM](https://user-images.githubusercontent.com/44193/176709011-bcab5abe-59d6-4ebf-92d0-1dd476bc191a.jpeg)

**Comment by kringkaste** [comment]
Fixed in release 1.0.6 for Craft 3 and 2.0.1 for Craft 4. Thanks for reporting it!
